### ISSUE TITLE
image port has changed 

### ISSUE THREAD

**Issue by ali-narimani** [Sermanes/bookstack-docker-k8s#1]
Hello,

it seems that @solidnerd has changed the port used for bookstack's http connection from 80 to 8080 in the latest version as explained in the latest change log in their [github](https://github.com/solidnerd/docker-bookstack) .

this is causing the liveness and readiness probes to fail and fall into a crash loop .

also please switch to clusterIp and add an ingress to the deployment for easier usage ,i used the following ingress and it seems to be working to tweak needed :
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  labels:
    name: bookstack-ingress
  name: bookstack-ingress
  namespace: bookstack
spec:
  rules:
    - host: stack.website.com
      http:
        paths:
          - backend:
              serviceName: bookstack-service
              servicePort: 80
            path: /
  tls:
    - hosts:
        - stack.website.com
      secretName: stack-tls
```
